### PR TITLE
Nep 105 change ui with ui kitten

### PR DESCRIPTION
**Pull request by shrijan-siris**
- [x] Include Jira Ticket No. in Title
- [ ] Write Unit Tests
- [x] Add screenshots whenever possible
- [ ] Make sure Azure Pipelines build succeed
- [ ] Adress Automated Code Reviews from Hound, Codacy and Deepscan
- [x] Add Reviewers

### CODE REVIEW

**Comment by shrijan-siris** [comment]
Screen Shot 2019-10-14 at 3 39 10 PM
Screen Shot 2019-10-14 at 3 41 08 PM

**Comment by shrijan-siris** [comment]
issue regarding scrollable tab menu with ui-kitten 
```https://github.com/akveo/react-native-ui-kitten/issues/634 ```

**Comment by syuraj** [comment]
it's looking good

**Comment by syuraj** [comment]
My headline section looked like this. It is a problem
image
@shrijan-siris

**Comment by shrijan-siris** [comment]
Screen Shot 2019-10-17 at 4 04 30 PM

**Pull request merged**
